# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: requirements-txt-fixer
-   repo: local
    hooks:
    -   id: system
        name: PyLint
        entry: python -m pylint.__main__
        language: system
        files: \.py$
-   repo: https://github.com/pre-commit/mirrors-csslint
    rev: v1.0.5
    hooks:
    -   id: csslint
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v7.25.0'
    hooks:
    -   id: eslint
        additional_dependencies:
        -   eslint@7.25.0
        -   eslint-config-airbnb@18.2.1
        args: ['--fix']
